name: Build Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run build
        run: python scripts/build.py
      - name: Check links
        run: python scripts/check_links.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: auto-build site'
          add: '*.html'
          default_author: github_actions
